name: RamEssentials2
version: '${project.version}'
main: dev.willram.ramEssentials2.RamEssentials2
api-version: '26.1.2'
folia-supported: true
dependencies:
  server:
    RamCore:
      load: BEFORE
      required: true
      join-classpath: true
